#!/bin/bash
git add './RemGraveInternal/src/*'
git add './RemGraveBase/src/*'
git add './GeneratedBase/src/*'
git add './GeneratedBase/generator.ruleset'
git add './GeneratedBase/base.ruleset'
git add './GeneratedGenerator/src/*'
git add './GeneratedGenerator/base/*'
git add './GeneratedGenerator/generator/*'
git add './add_all.sh'
git add './engraver.jar'