#!/bin/bash
git add './Cargon3/src/*'
git add './Classwise2/classwise2/*'
git add './Classwise2/cargon2/*'
git add './GeneratedCargon/*'
git add './OutputHelper/src/com/rem/output/helpers/*'
git add './LangHelpers/src/com/rem/lang/helpers/'
git add './LangHelpers/src/com/rem/lang/helpers/input/*'
git add './LangHelpers/src/com/rem/lang/helpers/output/*'
git add './add_all.sh'
git add './output_helpers.jar'
git add './classwise_helpers.jar'